#!/bin/bash

# -a archive mode
# -vv extra verbose, shows what was excluded and why
# -e ssh, use ssh
# src
# dest
# delete files that have been removed
# file specifying files to exclude
rsync -avve ssh ../raisedbyus/ groovemechanic:~/raisedby.us/ --delete --exclude-from 'exclude.rsync'
